server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://${PLUGTIFY_DB_HOST}:${PLUGTIFY_DB_PORT}/plugtify?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ${PLUGTIFY_DB_PASSWORD}
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      force: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

# specific application properties
application:
  spotify-client-id: ${SPOTIFY_CLIENT_ID}
  spotify-client-secret: ${SPOTIFY_CLIENT_SECRET}
