apiVersion: v1
kind: Service
metadata:
  name: plugtify-back-end
  labels:
    app: plugtify-back-end
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: plugtify-back-end
