apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plugtify-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: plugtify-ip-address
    networking.gke.io/managed-certificates: plugtify-certificacte
spec:
  backend:
    serviceName: plugtify-nodeport-service
    servicePort: 80
